param(
    [string]$AssistantName = "JClaw",
    # llama-server ports for main and worker models
    [int]$MainLlamaPort = 5002,
    [int]$WorkerLlamaPort = 5003,
    # Model filenames as served by llama-server (shown in /v1/models)
    [string]$MainModelFile = "Qwen_Qwen3.5-2B-bf16.gguf",
    [string]$WorkerModelFile = "omnicoder-9b-q8_0.gguf",
    [string]$MainAlias = "jclaw-main",
    [string]$WorkerAlias = "jclaw-worker",
    [int]$MaxConcurrentContainers = 3,
    [string]$ContainerImage = "nanoclaw-agent:latest",
    [string]$BindHost = "127.0.0.1"
)

function Resolve-FirstExistingPath {
    param([string[]]$Candidates)

    foreach ($candidate in $Candidates) {
        if ($candidate -and (Test-Path $candidate)) {
            return $candidate
        }
    }

    return $null
}

$repoRoot = Split-Path -Parent $PSScriptRoot
$envPath = Join-Path $repoRoot ".env"

$chromePath = Resolve-FirstExistingPath @(
    "$env:ProgramFiles\Google\Chrome\Application\chrome.exe",
    "$env:ProgramFiles(x86)\Google\Chrome\Application\chrome.exe",
    "$env:LOCALAPPDATA\Google\Chrome\Application\chrome.exe"
)

$firefoxPath = Resolve-FirstExistingPath @(
    "$env:ProgramFiles\Mozilla Firefox\firefox.exe",
    "$env:ProgramFiles(x86)\Mozilla Firefox\firefox.exe"
)

$operaPath = Resolve-FirstExistingPath @(
    "$env:LOCALAPPDATA\Programs\Opera\opera.exe",
    "$env:ProgramFiles\Opera\opera.exe",
    "$env:ProgramFiles(x86)\Opera\opera.exe",
    "$env:ProgramFiles\Opera\launcher.exe",
    "$env:ProgramFiles(x86)\Opera\launcher.exe"
)

$workerPort = if ($WorkerModelFile -and ($WorkerModelFile -ne $MainModelFile)) { $WorkerLlamaPort } else { $MainLlamaPort }
$mainEntry   = '{"url":"http://' + $BindHost + ':' + $MainLlamaPort + '/v1","model":"' + $MainModelFile   + '","key":"dummy-key"}'
$workerEntry = '{"url":"http://' + $BindHost + ':' + $workerPort      + '/v1","model":"' + $WorkerModelFile + '","key":"dummy-key"}'
$aliasJson   = '{"' + $MainAlias + '":' + $mainEntry + ',"' + $WorkerAlias + '":' + $workerEntry + '}'

$lines = @(
    "# Generated by scripts/setup-local-windows.ps1",
    "ASSISTANT_NAME=$AssistantName",
    "ASSISTANT_HAS_OWN_NUMBER=false",
    "",
    "CONTAINER_IMAGE=$ContainerImage",
    "MAX_CONCURRENT_CONTAINERS=$MaxConcurrentContainers",
    "",
    "JCLAW_MODEL_ALIASES=$aliasJson",
    "JCLAW_MODEL=$MainAlias",
    "JCLAW_WORKER_MODEL=$WorkerAlias",
    "JCLAW_FALLBACK_MODEL=$MainAlias",
    "JCLAW_USE_WORKER_MODEL_FOR_SCHEDULED=true",
    "",
    "CONTAINER_TIMEOUT=3600000",
    "IDLE_TIMEOUT=3600000",
    "JCLAW_HOST_BROWSER_HEADLESS=false",
    "JCLAW_HOST_BROWSER_IDLE_MS=300000"
)

if ($chromePath) {
    $lines += "JCLAW_CHROME_PATH=$chromePath"
}

if ($firefoxPath) {
    $lines += "JCLAW_FIREFOX_PATH=$firefoxPath"
}

if ($operaPath) {
    $lines += "JCLAW_OPERA_PATH=$operaPath"
}

Set-Content -Path $envPath -Value ($lines -join [Environment]::NewLine) -Encoding UTF8

Write-Host "Wrote $envPath"
Write-Host "Main model alias:   $MainAlias -> http://127.0.0.1:$MainLlamaPort/v1 ($MainModelFile)"
Write-Host "Worker model alias: $WorkerAlias -> http://127.0.0.1:$workerPort/v1 ($WorkerModelFile)"
Write-Host "Detected Chrome:  $chromePath"
Write-Host "Detected Firefox: $firefoxPath"
Write-Host "Detected Opera:   $operaPath"
Write-Host ""
Write-Host "Next:"
Write-Host "  1. Start the dual-model proxy with scripts/start-kobold-proxy.ps1"
Write-Host "  2. Start J Claw"